\documentclass[12pt]{article}
% \VignetteIndexEntry{CrypticIBDcheck using data from a case-control candidate gene study}
% \VignettePackage{CrypticIBDcheck}
\usepackage{hyperref,url}
\begin{document}
Please see the manuscript ``CrypticIBDcheck: an R package for checking cryptic relatedness
in nominally unrelated individuals'', published by Source Code for Biology and 
Medicine, and available at \\

\bigskip

\url{http://www.scfbm.org/content/8/1/5}
\end{document}
